//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Xbox.Tools.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Xbox.Tools.Shared.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} (Auxiliary Window).
        /// </summary>
        public static string AuxWindowTitleDocFmt {
            get {
                return ResourceManager.GetString("AuxWindowTitleDocFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string CancellingButtonText {
            get {
                return ResourceManager.GetString("CancellingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the specified development kit..
        /// </summary>
        public static string CannotConnectToKit {
            get {
                return ResourceManager.GetString("CannotConnectToKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the default development kit address?.
        /// </summary>
        public static string ConfirmChangingDefaultKit {
            get {
                return ResourceManager.GetString("ConfirmChangingDefaultKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this layout?.
        /// </summary>
        public static string ConfirmDeleteViewLayout {
            get {
                return ResourceManager.GetString("ConfirmDeleteViewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will erase all existing view layouts.  Are you sure you want to proceed?.
        /// </summary>
        public static string ConfirmRevertToDefaultWindowState {
            get {
                return ResourceManager.GetString("ConfirmRevertToDefaultWindowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A console with the alias &apos;{0}&apos; already exists in the list..
        /// </summary>
        public static string ConsoleAliasAlreadyExistsFmt {
            get {
                return ResourceManager.GetString("ConsoleAliasAlreadyExistsFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console aliases must be unique..
        /// </summary>
        public static string ConsoleAliasesMustBeUnique {
            get {
                return ResourceManager.GetString("ConsoleAliasesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing connection was forcibly closed by the remote host..
        /// </summary>
        public static string E_WSAECONNRESET {
            get {
                return ResourceManager.GetString("E_WSAECONNRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load window state.
        /// </summary>
        public static string ErrorLoadingWindowState {
            get {
                return ResourceManager.GetString("ErrorLoadingWindowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Force.
        /// </summary>
        public static string ForceButtonText {
            get {
                return ResourceManager.GetString("ForceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address does not appear to be valid.  Be sure that the name is entered correctly, or the IP address is in the correct format..
        /// </summary>
        public static string InvalidMachineAddress {
            get {
                return ResourceManager.GetString("InvalidMachineAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} (Main Window).
        /// </summary>
        public static string MainWindowTitleDocFmt {
            get {
                return ResourceManager.GetString("MainWindowTitleDocFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response from the specified address.  Be sure that the address is that of a development kit.  If the problem persists, you may need to restart the kit..
        /// </summary>
        public static string NoResponseFromSpecifiedAddress {
            get {
                return ResourceManager.GetString("NoResponseFromSpecifiedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background process is not responding to the request to cancel.  You can continue to wait, or you can force the process to terminate..
        /// </summary>
        public static string RequestIgnoringCancel {
            get {
                return ResourceManager.GetString("RequestIgnoringCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string SingleWindowTitleDocFmt {
            get {
                return ResourceManager.GetString("SingleWindowTitleDocFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _In.
        /// </summary>
        public static string TimelineContextMenuItem_ZoomIn {
            get {
                return ResourceManager.GetString("TimelineContextMenuItem_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _Out.
        /// </summary>
        public static string TimelineContextMenuItem_ZoomOut {
            get {
                return ResourceManager.GetString("TimelineContextMenuItem_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To _All.
        /// </summary>
        public static string TimelineContextMenuItem_ZoomToAll {
            get {
                return ResourceManager.GetString("TimelineContextMenuItem_ZoomToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To _Selection.
        /// </summary>
        public static string TimelineContextMenuItem_ZoomToSelection {
            get {
                return ResourceManager.GetString("TimelineContextMenuItem_ZoomToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        public static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized error code.
        /// </summary>
        public static string UnrecognizedErrorCode {
            get {
                return ResourceManager.GetString("UnrecognizedErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because the format of the persisted window state has changed, your window state has reverted to its default state..
        /// </summary>
        public static string WindowStateVersionMismatch {
            get {
                return ResourceManager.GetString("WindowStateVersionMismatch", resourceCulture);
            }
        }
    }
}
