//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectStudioPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectStudioPlugin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move _down.
        /// </summary>
        public static string Button_MoveDown {
            get {
                return ResourceManager.GetString("Button_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move _up.
        /// </summary>
        public static string Button_MoveUp {
            get {
                return ResourceManager.GetString("Button_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your graphics card does not support hardware processing, so your viewing experience will be limited..
        /// </summary>
        public static string Error_LimitedGraphics {
            get {
                return ResourceManager.GetString("Error_LimitedGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ; to separate entries.
        /// </summary>
        public static string Metadata_EditArray_ToolTip {
            get {
                return ResourceManager.GetString("Metadata_EditArray_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string Metadata_InvalidData {
            get {
                return ResourceManager.GetString("Metadata_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Plugin_Enabled_ToolTip {
            get {
                return ResourceManager.GetString("Plugin_Enabled_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Plugin &quot;{0}&quot; of type &quot;{1}&quot; in &quot;{2}&quot;: empty ID.
        /// </summary>
        public static string Plugin_Error_BadPluginId {
            get {
                return ResourceManager.GetString("Plugin_Error_BadPluginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Plugin &quot;{0}&quot; of type &quot;{1}&quot; in &quot;{2}&quot;: duplicate ID to Plugin &quot;{3}&quot; of type &quot;{4}&quot;.
        /// </summary>
        public static string Plugin_Error_DuplicatePluginId {
            get {
                return ResourceManager.GetString("Plugin_Error_DuplicatePluginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Plugins.
        /// </summary>
        public static string PluginMetadataSettings_Title {
            get {
                return ResourceManager.GetString("PluginMetadataSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D View Settings.
        /// </summary>
        public static string PluginViewSettings_2DTitle {
            get {
                return ResourceManager.GetString("PluginViewSettings_2DTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D View Settings.
        /// </summary>
        public static string PluginViewSettings_3DTitle {
            get {
                return ResourceManager.GetString("PluginViewSettings_3DTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Settings.
        /// </summary>
        public static string PluginViewSettings_WpfTitle {
            get {
                return ResourceManager.GetString("PluginViewSettings_WpfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the cursor over a 2D image view to inspect the pixel properties..
        /// </summary>
        public static string PropView_Prompt {
            get {
                return ResourceManager.GetString("PropView_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value supplied.
        /// </summary>
        public static string Validate_InvalidData_Error {
            get {
                return ResourceManager.GetString("Validate_InvalidData_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value supplied.
        /// </summary>
        public static string Validation_NoValue_Error {
            get {
                return ResourceManager.GetString("Validation_NoValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default view.
        /// </summary>
        public static string View_DefaultView_Button_ToolTip {
            get {
                return ResourceManager.GetString("View_DefaultView_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front view.
        /// </summary>
        public static string View_FrontView_Button_ToolTip {
            get {
                return ResourceManager.GetString("View_FrontView_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left view.
        /// </summary>
        public static string View_LeftView_Button_ToolTip {
            get {
                return ResourceManager.GetString("View_LeftView_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONITOR:.
        /// </summary>
        public static string View_Monitor_Label {
            get {
                return ResourceManager.GetString("View_Monitor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSPECT:.
        /// </summary>
        public static string View_Playback_Label {
            get {
                return ResourceManager.GetString("View_Playback_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string View_Settings_Button_ToolTip {
            get {
                return ResourceManager.GetString("View_Settings_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top view.
        /// </summary>
        public static string View_TopView_Button_ToolTip {
            get {
                return ResourceManager.GetString("View_TopView_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom {0}%.
        /// </summary>
        public static string View_Zoom_ComboBoxItem_Format {
            get {
                return ResourceManager.GetString("View_Zoom_ComboBoxItem_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        public static string View_Zoom100_ComboBoxItem {
            get {
                return ResourceManager.GetString("View_Zoom100_ComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200%.
        /// </summary>
        public static string View_Zoom200_ComboBoxItem {
            get {
                return ResourceManager.GetString("View_Zoom200_ComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300%.
        /// </summary>
        public static string View_Zoom300_ComboBoxItem {
            get {
                return ResourceManager.GetString("View_Zoom300_ComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400%.
        /// </summary>
        public static string View_Zoom400_ComboBoxItem {
            get {
                return ResourceManager.GetString("View_Zoom400_ComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%.
        /// </summary>
        public static string View_Zoom50_ComboBoxItem {
            get {
                return ResourceManager.GetString("View_Zoom50_ComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75%.
        /// </summary>
        public static string View_Zoom75_ComboBoxItem {
            get {
                return ResourceManager.GetString("View_Zoom75_ComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string View_ZoomIn_Button_ToolTip {
            get {
                return ResourceManager.GetString("View_ZoomIn_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string View_ZoomOut_Button_ToolTip {
            get {
                return ResourceManager.GetString("View_ZoomOut_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to fit.
        /// </summary>
        public static string View_ZoomToFit_Button_ToolTip {
            get {
                return ResourceManager.GetString("View_ZoomToFit_Button_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to fit.
        /// </summary>
        public static string View_ZoomToFit_ComboBoxItem {
            get {
                return ResourceManager.GetString("View_ZoomToFit_ComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Default view.
        /// </summary>
        public static string ViewMenu_Rotate_Default_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Rotate_Default_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Front view.
        /// </summary>
        public static string ViewMenu_Rotate_Front_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Rotate_Front_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Left view.
        /// </summary>
        public static string ViewMenu_Rotate_Left_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Rotate_Left_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Top view.
        /// </summary>
        public static string ViewMenu_Rotate_Top_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Rotate_Top_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ViewMenu_Settings_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Settings_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _100%.
        /// </summary>
        public static string ViewMenu_Zoom100_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Zoom100_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _200%.
        /// </summary>
        public static string ViewMenu_Zoom200_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Zoom200_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _300%.
        /// </summary>
        public static string ViewMenu_Zoom300_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Zoom300_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _400%.
        /// </summary>
        public static string ViewMenu_Zoom400_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Zoom400_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _50%.
        /// </summary>
        public static string ViewMenu_Zoom50_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Zoom50_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _75%.
        /// </summary>
        public static string ViewMenu_Zoom75_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_Zoom75_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _in.
        /// </summary>
        public static string ViewMenu_ZoomIn_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_ZoomIn_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom _out.
        /// </summary>
        public static string ViewMenu_ZoomOut_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_ZoomOut_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zoom to fit.
        /// </summary>
        public static string ViewMenu_ZoomToFit_MenuItem {
            get {
                return ResourceManager.GetString("ViewMenu_ZoomToFit_MenuItem", resourceCulture);
            }
        }
    }
}
