//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardKinectStudioPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StandardKinectStudioPlugin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Accessory_Plugin_Title {
            get {
                return ResourceManager.GetString("Accessory_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Floor plane (requires Body).
        /// </summary>
        public static string Accessory_RenderFloorPlane_CheckBox {
            get {
                return ResourceManager.GetString("Accessory_RenderFloorPlane_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Frustum.
        /// </summary>
        public static string Accessory_RenderFrustum_CheckBox {
            get {
                return ResourceManager.GetString("Accessory_RenderFrustum_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Orientation cube.
        /// </summary>
        public static string Accessory_RenderOrientationCube_CheckBox {
            get {
                return ResourceManager.GetString("Accessory_RenderOrientationCube_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Array.
        /// </summary>
        public static string AdvancedMetadataArrayPlugin_Title {
            get {
                return ResourceManager.GetString("AdvancedMetadataArrayPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is _audible.
        /// </summary>
        public static string Audio_AudibleTrack_CheckBox {
            get {
                return ResourceManager.GetString("Audio_AudibleTrack_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam.
        /// </summary>
        public static string Audio_Beam_CheckBox {
            get {
                return ResourceManager.GetString("Audio_Beam_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Angle: (none).
        /// </summary>
        public static string Audio_Beam_Invalid_Label {
            get {
                return ResourceManager.GetString("Audio_Beam_Invalid_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Angle: {0}.
        /// </summary>
        public static string Audio_Beam_Label_Format {
            get {
                return ResourceManager.GetString("Audio_Beam_Label_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialize audio player. Audio will not be audible..
        /// </summary>
        public static string Audio_Error_CannotInitializePlayer {
            get {
                return ResourceManager.GetString("Audio_Error_CannotInitializePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC0.
        /// </summary>
        public static string Audio_Mic0 {
            get {
                return ResourceManager.GetString("Audio_Mic0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC 0.
        /// </summary>
        public static string Audio_Mic0_CheckBox {
            get {
                return ResourceManager.GetString("Audio_Mic0_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC1.
        /// </summary>
        public static string Audio_Mic1 {
            get {
                return ResourceManager.GetString("Audio_Mic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC 1.
        /// </summary>
        public static string Audio_Mic1_CheckBox {
            get {
                return ResourceManager.GetString("Audio_Mic1_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC2.
        /// </summary>
        public static string Audio_Mic2 {
            get {
                return ResourceManager.GetString("Audio_Mic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC 2.
        /// </summary>
        public static string Audio_Mic2_CheckBox {
            get {
                return ResourceManager.GetString("Audio_Mic2_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC3.
        /// </summary>
        public static string Audio_Mic3 {
            get {
                return ResourceManager.GetString("Audio_Mic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC 3.
        /// </summary>
        public static string Audio_Mic3_CheckBox {
            get {
                return ResourceManager.GetString("Audio_Mic3_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT.
        /// </summary>
        public static string Audio_Output {
            get {
                return ResourceManager.GetString("Audio_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Output.
        /// </summary>
        public static string Audio_Output_CheckBox {
            get {
                return ResourceManager.GetString("Audio_Output_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio_Plugin_Title {
            get {
                return ResourceManager.GetString("Audio_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires an Audio stream to be available.
        /// </summary>
        public static string Audio_Requirements_ToolTip {
            get {
                return ResourceManager.GetString("Audio_Requirements_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPKBL.
        /// </summary>
        public static string Audio_SpeakerBL {
            get {
                return ResourceManager.GetString("Audio_SpeakerBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPK BL.
        /// </summary>
        public static string Audio_SpeakerBL_CheckBox {
            get {
                return ResourceManager.GetString("Audio_SpeakerBL_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPKBR.
        /// </summary>
        public static string Audio_SpeakerBR {
            get {
                return ResourceManager.GetString("Audio_SpeakerBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPK BR.
        /// </summary>
        public static string Audio_SpeakerBR_CheckBox {
            get {
                return ResourceManager.GetString("Audio_SpeakerBR_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPKC.
        /// </summary>
        public static string Audio_SpeakerC {
            get {
                return ResourceManager.GetString("Audio_SpeakerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPK C.
        /// </summary>
        public static string Audio_SpeakerC_CheckBox {
            get {
                return ResourceManager.GetString("Audio_SpeakerC_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPKL.
        /// </summary>
        public static string Audio_SpeakerL {
            get {
                return ResourceManager.GetString("Audio_SpeakerL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPK L.
        /// </summary>
        public static string Audio_SpeakerL_CheckBox {
            get {
                return ResourceManager.GetString("Audio_SpeakerL_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPKLFE.
        /// </summary>
        public static string Audio_SpeakerLFE {
            get {
                return ResourceManager.GetString("Audio_SpeakerLFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPK LFE.
        /// </summary>
        public static string Audio_SpeakerLFE_CheckBox {
            get {
                return ResourceManager.GetString("Audio_SpeakerLFE_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPKR.
        /// </summary>
        public static string Audio_SpeakerR {
            get {
                return ResourceManager.GetString("Audio_SpeakerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPK R.
        /// </summary>
        public static string Audio_SpeakerR_CheckBox {
            get {
                return ResourceManager.GetString("Audio_SpeakerR_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPKSL.
        /// </summary>
        public static string Audio_SpeakerSL {
            get {
                return ResourceManager.GetString("Audio_SpeakerSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPK SL.
        /// </summary>
        public static string Audio_SpeakerSL_CheckBox {
            get {
                return ResourceManager.GetString("Audio_SpeakerSL_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPKSR.
        /// </summary>
        public static string Audio_SpeakerSR {
            get {
                return ResourceManager.GetString("Audio_SpeakerSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPK SR.
        /// </summary>
        public static string Audio_SpeakerSR_CheckBox {
            get {
                return ResourceManager.GetString("Audio_SpeakerSR_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body_Plugin_Title {
            get {
                return ResourceManager.GetString("Body_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bodies.
        /// </summary>
        public static string Body_RenderBodies_CheckBox {
            get {
                return ResourceManager.GetString("Body_RenderBodies_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hands.
        /// </summary>
        public static string Body_RenderHands_CheckBox {
            get {
                return ResourceManager.GetString("Body_RenderHands_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body information.
        /// </summary>
        public static string Body_RenderInfo_CheckBox {
            get {
                return ResourceManager.GetString("Body_RenderInfo_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint orientations.
        /// </summary>
        public static string Body_RenderJointOrientations_CheckBox {
            get {
                return ResourceManager.GetString("Body_RenderJointOrientations_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a Body stream to be available.
        /// </summary>
        public static string Body_Requirements_ToolTip {
            get {
                return ResourceManager.GetString("Body_Requirements_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Index.
        /// </summary>
        public static string BodyIndex_Plugin_Title {
            get {
                return ResourceManager.GetString("BodyIndex_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Index.
        /// </summary>
        public static string BodyIndex_Property_BodyIndex_Label {
            get {
                return ResourceManager.GetString("BodyIndex_Property_BodyIndex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string BodyIndex_Property_BodyIndex_NoBody {
            get {
                return ResourceManager.GetString("BodyIndex_Property_BodyIndex_NoBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Index values.
        /// </summary>
        public static string BodyIndex_Property_Title {
            get {
                return ResourceManager.GetString("BodyIndex_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a Body Index stream to be available.
        /// </summary>
        public static string BodyIndex_Requirements_ToolTip {
            get {
                return ResourceManager.GetString("BodyIndex_Requirements_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color_Plugin_Title {
            get {
                return ResourceManager.GetString("Color_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Color_Property_Blue_Label {
            get {
                return ResourceManager.GetString("Color_Property_Blue_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Color_Property_Green_Label {
            get {
                return ResourceManager.GetString("Color_Property_Green_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Color_Property_Red_Label {
            get {
                return ResourceManager.GetString("Color_Property_Red_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color_Property_Title {
            get {
                return ResourceManager.GetString("Color_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a Color stream to be available.
        /// </summary>
        public static string Color_Requirements_ToolTip {
            get {
                return ResourceManager.GetString("Color_Requirements_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Plugin.
        /// </summary>
        public static string Depth_Plugin_Title {
            get {
                return ResourceManager.GetString("Depth_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth (mm).
        /// </summary>
        public static string Depth_Property_Depth_Label {
            get {
                return ResourceManager.GetString("Depth_Property_Depth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth values.
        /// </summary>
        public static string Depth_Property_Title {
            get {
                return ResourceManager.GetString("Depth_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a Depth stream to be available.
        /// </summary>
        public static string Depth_Requirements_ToolTip {
            get {
                return ResourceManager.GetString("Depth_Requirements_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface can be _textured.
        /// </summary>
        public static string Depth_Texture_CheckBox {
            get {
                return ResourceManager.GetString("Depth_Texture_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Color ramp.
        /// </summary>
        public static string Depth_ViewType_2D_Color_Radio {
            get {
                return ResourceManager.GetString("Depth_ViewType_2D_Color_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Grey ramp.
        /// </summary>
        public static string Depth_ViewType_2D_Grey_Radio {
            get {
                return ResourceManager.GetString("Depth_ViewType_2D_Grey_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Color Point Cloud.
        /// </summary>
        public static string Depth_ViewType_3D_Color_Radio {
            get {
                return ResourceManager.GetString("Depth_ViewType_3D_Color_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Grey Point Cloud.
        /// </summary>
        public static string Depth_ViewType_3D_Grey_Radio {
            get {
                return ResourceManager.GetString("Depth_ViewType_3D_Grey_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Surface with Normal.
        /// </summary>
        public static string Depth_ViewType_3D_Surface_Radio {
            get {
                return ResourceManager.GetString("Depth_ViewType_3D_Surface_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View type.
        /// </summary>
        public static string Depth_ViewType_GroupBox {
            get {
                return ResourceManager.GetString("Depth_ViewType_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplification.
        /// </summary>
        public static string Ir_Amplification_Prompt {
            get {
                return ResourceManager.GetString("Ir_Amplification_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amplification A in A * V^Gamma, where V is the normalized Value between 0 and 1.
        /// </summary>
        public static string Ir_Amplification_ToolTip {
            get {
                return ResourceManager.GetString("Ir_Amplification_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        public static string Ir_Gamma_Prompt {
            get {
                return ResourceManager.GetString("Ir_Gamma_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Gamma in A * V^Gamma, where V is the normalized Value between 0 and 1.
        /// </summary>
        public static string Ir_Gamma_ToolTip {
            get {
                return ResourceManager.GetString("Ir_Gamma_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared Plugin.
        /// </summary>
        public static string Ir_Plugin_Title {
            get {
                return ResourceManager.GetString("Ir_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string Ir_Property_Intensity_Label {
            get {
                return ResourceManager.GetString("Ir_Property_Intensity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR values.
        /// </summary>
        public static string Ir_Property_Title {
            get {
                return ResourceManager.GetString("Ir_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires an IR stream to be available.
        /// </summary>
        public static string Ir_Requirements_ToolTip {
            get {
                return ResourceManager.GetString("Ir_Requirements_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Metadata_ViewArray_Add_Button {
            get {
                return ResourceManager.GetString("Metadata_ViewArray_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count = {0}.
        /// </summary>
        public static string Metadata_ViewArray_CountFormat {
            get {
                return ResourceManager.GetString("Metadata_ViewArray_CountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Metadata_ViewArray_Delete_Button {
            get {
                return ResourceManager.GetString("Metadata_ViewArray_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Metadata_ViewArray_EditButton {
            get {
                return ResourceManager.GetString("Metadata_ViewArray_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move _down.
        /// </summary>
        public static string Metadata_ViewArray_MoveDown_Button {
            get {
                return ResourceManager.GetString("Metadata_ViewArray_MoveDown_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move _up.
        /// </summary>
        public static string Metadata_ViewArray_MoveUp_Button {
            get {
                return ResourceManager.GetString("Metadata_ViewArray_MoveUp_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Array.
        /// </summary>
        public static string Metadata_ViewArray_Title {
            get {
                return ResourceManager.GetString("Metadata_ViewArray_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Metadata_ViewArray_ViewButton {
            get {
                return ResourceManager.GetString("Metadata_ViewArray_ViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings for this plugin.
        /// </summary>
        public static string NoViewSettings_Text {
            get {
                return ResourceManager.GetString("NoViewSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Property_X_Label {
            get {
                return ResourceManager.GetString("Property_X_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Property_Y_Label {
            get {
                return ResourceManager.GetString("Property_Y_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Infrared Plugin.
        /// </summary>
        public static string RawIr_Plugin_Title {
            get {
                return ResourceManager.GetString("RawIr_Plugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth (mm).
        /// </summary>
        public static string RawIr_Property_Depth_Label {
            get {
                return ResourceManager.GetString("RawIr_Property_Depth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string RawIr_Property_Intensity_Label {
            get {
                return ResourceManager.GetString("RawIr_Property_Intensity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw IR/Depth values.
        /// </summary>
        public static string RawIr_Property_Title {
            get {
                return ResourceManager.GetString("RawIr_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a Raw IR stream to be available.
        /// </summary>
        public static string RawIr_Requirements_ToolTip {
            get {
                return ResourceManager.GetString("RawIr_Requirements_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface can be _textured.
        /// </summary>
        public static string RawIr_Texture_CheckBox {
            get {
                return ResourceManager.GetString("RawIr_Texture_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth _color ramp.
        /// </summary>
        public static string RawIr_ViewType_2D_Color_Radio {
            get {
                return ResourceManager.GetString("RawIr_ViewType_2D_Color_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth _grey ramp.
        /// </summary>
        public static string RawIr_ViewType_2D_Grey_Radio {
            get {
                return ResourceManager.GetString("RawIr_ViewType_2D_Grey_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Infrared.
        /// </summary>
        public static string RawIr_ViewType_2D_Ir_Radio {
            get {
                return ResourceManager.GetString("RawIr_ViewType_2D_Ir_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth _color Point Cloud.
        /// </summary>
        public static string RawIr_ViewType_3D_Color_Radio {
            get {
                return ResourceManager.GetString("RawIr_ViewType_3D_Color_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth _grey Point Cloud.
        /// </summary>
        public static string RawIr_ViewType_3D_Grey_Radio {
            get {
                return ResourceManager.GetString("RawIr_ViewType_3D_Grey_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Infrared.
        /// </summary>
        public static string RawIr_ViewType_3D_Ir_Radio {
            get {
                return ResourceManager.GetString("RawIr_ViewType_3D_Ir_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Surface with Normal.
        /// </summary>
        public static string RawIr_ViewType_3D_Surface_Radio {
            get {
                return ResourceManager.GetString("RawIr_ViewType_3D_Surface_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View type.
        /// </summary>
        public static string RawIr_ViewType_GroupBox {
            get {
                return ResourceManager.GetString("RawIr_ViewType_GroupBox", resourceCulture);
            }
        }
    }
}
